on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get astilectron
      run: go get -u github.com/asticode/go-astilectron
    - name: Get astilectron bundler
      run: go get -u github.com/asticode/go-astilectron-bundler/...
    - name: build
      run: astilectron-bundler
    - uses: actions/upload-artifact@v2
      with:
        name: VegaWalletGUI-linux-amd64
        path: output/linux-amd64/
      if: matrix.os == 'ubuntu-latest' 
    - uses: actions/upload-artifact@v2
      with:
        name: VegaWalletGUI-windows-amd64.exe
        path: output/windows-amd64/
      if: matrix.os == 'windows-latest' 
    - name: Zip Folder
      run: zip -r VegaWalletGUI-macosx-amd64.app.zip output/darwin-amd64/VegaWalletGUI-macosx-amd64.app
      if: matrix.os == 'macos-latest' 
    - uses: actions/upload-artifact@v2
      with:
        name: VegaWalletGUI-macosx-amd64.app.zip
      if: matrix.os == 'macos-latest' 
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: VegaWalletGUI-linux-amd64
        path: VegaWalletGUI-linux-amd64
    - uses: actions/download-artifact@v2
      with:
        name: VegaWalletGUI-windows-amd64.exe
        path: VegaWalletGUI-windows-amd64.exe
    - uses: actions/download-artifact@v2
      with:
        name: VegaWalletGUI-macosx-amd64.app
        path: VegaWalletGUI-macosx-amd64.app
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Vega Wallet GUI Snapshot"
        files: |
          VegaWalletGUI-linux-amd64
          VegaWalletGUI-windows-amd64.exe
          VegaWalletGUI-macosx-amd64.app
