on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get astilectron
      run: go get -u github.com/asticode/go-astilectron
    - name: Get astilectron bundler
      run: go get -u github.com/asticode/go-astilectron-bundler/...
    - name: build
      run: astilectron-bundler -d -w -l
    - uses: actions/upload-artifact@v2
      with:
        name: "Vega Wallet GUI"
        path: output/linux-amd64/
    - uses: actions/upload-artifact@v2
      with:
        name: "Vega Wallet GUI.exe"
        path: output/windows-amd64/
    - uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r VegaWalletGUI-macosx-amd64.app.zip "output/darwin-amd64/Vega Wallet GUI.app"
    - uses: actions/upload-artifact@v2
      with:
        name: VegaWalletGUI-macosx-amd64.app.zip
        path: .
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "0.1.0"
        prerelease: true
        title: "Vega Wallet GUI Snapshot"
        files: |
          "output/linux-amd64/Vega Wallet GUI"
          "output/windows-amd64/Vega Wallet GUI.exe"
          VegaWalletGUI-macosx-amd64.app.zip
